namespace KerbalKontroller.Config
{
    public class PinConfiguration
    {
        public byte LeftJoyStickX { get; set; }
        public byte LeftJoyStickY { get; set; }
        public byte ExtraLeftJoyStickX { get; set; }
        public byte ExtraLeftJoyStickY { get; set; }
        public byte RightJoyStickX { get; set; }
        public byte RightJoyStickY { get; set; }
        public byte ExtraRightJoyStickX { get; set; }
        public byte ExtraRightJoyStickY { get; set; }
        public byte AnalogThrottle { get; set; }
        public byte FullThrottleButton { get; set; }
        public byte CutOffThrottleButton { get; set; }
        public byte StageButton { get; set; }
        public byte AbortButton { get; set; }
        public byte LandingGearSwitch { get; set; }
        public byte BrakesSwitch { get; set; }
        public byte BrakesButton { get; set; }
        public byte LightsSwitch { get; set; }
        public byte SASSwitch { get; set; }
        public byte RCSSwitch { get; set; }
        public byte PrecisionSwitch { get; set; }
        public byte Action1Button { get; set; }
        public byte Action2Button { get; set; }
        public byte Action3Button { get; set; }
        public byte Action4Button { get; set; }
        public byte Action5Button { get; set; }
        public byte Action6Button { get; set; }
        public byte Action7Button { get; set; }
        public byte Action8Button { get; set; }
        public byte Action9Button { get; set; }
        public byte Action10Button { get; set; }
        public byte SASFreeButton { get; set; }
        public byte SASProgradeButton { get; set; }
        public byte SASRetrogadeButton { get; set; }
        public byte SASRadialInButton { get; set; }
        public byte SASRadialOutButton { get; set; }
        public byte SASNormalButton { get; set; }
        public byte SASAntiNormalButton { get; set; }
        public byte SASTargetButton { get; set; }
        public byte SASAntiTargetButton { get; set; }
        public byte KerbalUseButton { get; set; }
        public byte KerbalBoard { get; set; }
        public byte KerbalParachute { get; set; }
        public byte KerbalJetPack { get; set; }
        public byte OrbitalViewButton { get; set; }
        public byte TimeWarpPlusButton { get; set; }
        public byte TimeWarpMinusButton { get; set; }
        public byte NextVesselButton { get; set; }
        public byte PreviousVesselButton { get; set; }
        public byte PauseButton { get; set; }
        public byte QuickSaveButton { get; set; }
        public byte QuickLoadButton { get; set; }
        public byte LandingGearLed { get; set; }
        public byte BrakesLed { get; set; }
        public byte LightsLed { get; set; }
        public byte SASLed { get; set; }
        public byte RCSLed { get; set; }
        public byte PrecisionLed { get; set; }
        public byte SASFreeLed { get; set; }
        public byte SASProgradeLed { get; set; }
        public byte SASRetrogadeLed { get; set; }
        public byte SASRadialInLed { get; set; }
        public byte SASRadialOutLed { get; set; }
        public byte SASNormalLed { get; set; }
        public byte SASAntiNormalLed { get; set; }
        public byte SASTargetLed { get; set; }
        public byte SASAntiTargetLed { get; set; }
    }
}
